### ISSUE TITLE
要望：ノイズゲート式のミュートシステム

### ISSUE THREAD

**Issue by ni1chigo2115** [TyounanMOTI/AudioTeapot#6]
監視しているマイクの入力が一定を超えたらミュートを解除、その後音量が一定以下の無音判定になったあと一定時間経ったら自動的にミュートするものがほしいです。
VRCで使われているものと同じマイクを監視して、ノイズゲートをこちらで用意することによって
ノイズゲートのシステムをTEAPOTで乗っ取ってしまおうという考えです
演奏はしないが長時間の細やかな息遣いが必要な演技が必要・・・だったりするときに
ノイズゲートそのものを乗っ取るシステムがあると使用者側でVRCのノイズゲートではなく
TEAPOTのノイズゲートを使用できるので助かると思います。（無論VRCのノイズゲートは出だしに問題があることは承知している）

**Comment by TyounanMOTI** [comment]
ご要望ありがとうございます。楽しそうなのでぜひ実装してみたいところです。
featureブランチに実装していって、ベータリリースを重ねる感じで開発していきます。随時フィードバックをいただけると助かります。
最もシンプルなノイズゲートのパラメータは以下のとおりになります：

- スレッショルド：ミュート解除・開始のピーク値 (dBFs)
- ホールド：ミュート解除してから解除を維持する時間。この間はスレッショルドを下回ってもミュート開始しない

最終的にはこのあたりまで実装したいところです：

- オープンスレッショルド：ミュート解除するピーク値 (dBFs)
- クローズスレッショルド：ミュート開始するピーク値 (dBFs)
- アタック：ミュート解除してからどれだけの時間で最大音量に達するか
- ホールド
- リリース：ミュート開始してからどれだけの時間で最小音量に達するか
- レンジ（フロア）：ミュートしているときにどれだけ減衰させるか (dB)

ここまでくるとUIを練ったりモニターしたくなってくるので、まあまあ時間はかかりそうです。シンプルなところから段階的に進めていきます。

**Comment by ni1chigo2115** [comment]
ありがとうございます、開発頑張ってください
